- lib/Text/Xslate/Syntax/Kolon.pm
I got several bugs because I did not understand 'include' very well, so add some doc.
> add doc about var precedece when use include

- lib/Text/Xslate.pm
It's better if the default cache dir is configurable in program.
This also fixes #135 and #137.
> make $Text::Xslate::DEFAULT_CACHE_DIR to configure the default cache dir

- src/Text-Xslate.xs
- t/900_bugs/045_issue130.t
Text::Xslate::load_file returns value and it is pushed on stack. But tx_invoke_load_file function does not pop stack(and never use it), then stack pointer is incorrect after calling tx_invoke_load_file.
This patch sets G_DISCARD flag to call_method(Text::Xslate::load_file) for getting rid of return value from stack automatically.
I confirmed [test1](https://github.com/xslate/p5-Text-Xslate/issues/130#issue-42141613), [test2](https://github.com/xslate/p5-Text-Xslate/issues/130#issuecomment-113747980) are passed with this change.
Please review this patch. This is related to #130.
> Fix issue130

- .travis.yml
Because dependency module 'Test::Vars' requires Perl 5.10 or higher.
See
- https://travis-ci.org/xslate/p5-Text-Xslate/jobs/76598190
> Remove 5.8 from CI

- t/900_bugs/023_deploy_problem.t
mtime of file is not updated after closing file on DragonflyBSD file
system, such as UFS. This causes test failure. It seems mtime is update
after fflush and fsync.
Test are failed on many Dragonfly BSD environment.
- http://matrix.cpantesters.org/?dist=Text-Xslate%203.3.7;os=dragonfly;reports=1
> Fix test for DragonflyBSD

- src/Text-Xslate.xs
- t/900_bugs/046_issue156.t
Check array element is not NULL. Because AvARRAY element is NULL instead of &PL_sv_undef since Perl 5.19.3.
See also
- https://github.com/Perl/perl5/commit/ce0d59fdd1c7d145efdf6bf8da56a259fed483e4
This is related to #156, #157.
CC: @xinminglai Could you check this patch ?
> Fix issue 156 segmentation fault issue

- lib/Text/Xslate.pm
The documentation was rendered incorrectly on metacpan, so here's a fix.
> DOC Add an extra newline before =head1 SEE ALSO

- lib/Text/Xslate/PP.pm
- src/xslate_opcode.inc
- t/900_bugs/047_undef_concat.t
Generally xslate handles undefined `$variables` silently. But in the case of
concatenation with the ~ operator, it dies with the message
Use of uninitialized value in subroutine entry
This change to the concat operator handling makes `$A ~ $B` not fail if either
is undef, which is consistent with the rest of xslate's behavior.
> fix concat operator with undef variables

- src/xslate_opcode.inc
- t/900_bugs/048_issue172.t
> Fix issue 172

- lib/Text/Xslate.pm
> Fixed typo in documentation

- xt/200_depended.t
In xt/200_depended.t, we run tests for not only Text::Xslate::Bridge::TT2Like and Catalyst::View::Xslate, but also their dependencies.
I don't think this is necessary, so skip running tests for the dependencies;
this makes travis-ci much faster.
> xt/200_depended.t: installdeps with --notest

- cpanfile
- lib/Text/Xslate.pm
- lib/Text/Xslate/PP.pm
- lib/Text/Xslate/PP/Opcode.pm
- src/Text-Xslate.xs
- src/xslate.h
This PR improves perl 5.8 support.
Currently Xslate cannot be built on perl 5.8 with Devel::PPPort 3.33+.
This commit will fix this.
See also https://github.com/mhx/Devel-PPPort/issues/42
Currently [t/900_bugs/030_issue71.t](https://github.com/xslate/p5-Text-Xslate/blob/master/t/900_bugs/030_issue71.t) fails on perl 5.8.
In recent perl, SvUPGRADE(av, SVt_PVAV) makes the av AvREAL_only,
so that av_fill() frees deleted elements.
https://github.com/Perl/perl5/blob/v5.26.1/sv.c#L1357
https://github.com/Perl/perl5/blob/v5.26.1/av.c#L860-L865
On the other hand, in perl 5.8, SvUPGRADE(av, SVt_PVAV) does **NOT** make the av AvREAL_only,
so that av_fill() does **NOT** free deleted elements, and it implies memory leaks.
https://github.com/Perl/perl5/blob/perl-5.8.5/sv.c#L1462-L1476 …
> improves perl 5.8 support

- cpanfile
- t/010_internals/008_files.t
- t/lib/Util.pm
On windows, t\010_internals\007_compile_errs.t sometimes fails.
See https://ci.appveyor.com/project/gfx/p5-text-xslate/build/1.0.4
t\010_internals\007_compile_errs.t assumes that the mtime of template files for it are now.
On windows, File::Copy::copy equals Win32::CopyFile, which preserves the original mtime.
So the mtime of template files for test may not be now.
This PR sets mtime now manually on windows.
> fix test for windows

- t/900_bugs/040_issue95.t
The constructors in 040_issue95.t were not specifying a value for 'cache_dir'.
As a consequence, directories and files created during testing were being
placed underneath user's home directory and not being removed automatically.
Have those directories and files be created in temporary directories with
automatic cleanup.
> Guarantee that test cleans up after itself.

- t/020_interface/017_validate.t
- t/040_tterse/008_methods.t
- t/040_tterse/018_process.t
- t/900_bugs/019_nested_mm.t
- t/900_bugs/033_ex_safe_render.t
- t/900_bugs/045_issue130.t
- t/900_bugs/046_issue156.t
Test was leaving data in ~/.xslate_cache.  Tests should use tempdirs rather
than leaving data under tester's home directory.
Follow-up to last comment in https://github.com/xslate/p5-Text-Xslate/pull/189
> Ensure that test cleans up after itself.

- .gitignore
- builder/MyBuilder.pm
- src/xslate_methods.xs
Fix #192 
In old perls such as 5.8.8, it seems that we should set XS_VERSION to build src/xslate_methods.c:
```
[root@419bfe767e97 p5-Text-Xslate]# gcc -Isrc -I/usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi/CORE -fPIC -Wall -Wextra -Wdeclaration-after-statement -c -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -Wdeclaration-after-statement -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/gdbm -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -E src/xslate_methods.c | grep Text::Xslate::Methods::_guts
SV *my_cxt_sv = *Perl_hv_fetch(my_perl, (*Perl_Imodglobal_ptr(my_perl)),"Text::Xslate::Methods::_guts" XS_VERSION,sizeof("Text::Xslate::Methods::_guts" XS_VERSION)-1,(1)); my_cxt_t …
```
> define XS_VERSION

- lib/Text/Xslate/Syntax/TTerse.pm
A couple of examples are missing the % in the close %]. Thank you!
> Simple syntax typos in POD

- src/xslate_methods.xs
related to #199.
When dealing with long arrays (about 123 elements), `EXTEND()` macro changes `SP` but `MARK` hasn't changed. Causes segfault because `MARK` keeps pointing to the old stack.
`MEXTEND ()` do Same thing as `EXTEND ()`, but update mark register too.
> fix a segfault on array join

- t/900_bugs/032_issue79.t
Module::Build or "prove" pass INC via PERL5LIB environment variable,
so we do not need to set INC by ourselves.
This will fix #202
> do not set INC manually

- t/010_internals/008_files.t
https://www.cpantesters.org/cpan/report/694c1696-3809-11ec-8d11-e947f7ad8bd4
```
t/010_internals/008_files.t ..................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 
```
Currently we use `$^T + 10` to update file modification time,
but if the test take a lot of time for some reasons, then `$^T + 10` may not update file modification time.
Use `time + 10` to make sure we update file modification time.
> fix t/010_internals/008_files.t
